platform:
  - x64

install:
  - mkdir C:\bin
  - ps: Invoke-WebRequest -UserAgent wget -Uri "https://ci.appveyor.com/api/projects/snmsts/roswell-en89n/artifacts/Roswell-x86_64.zip?branch=master&job=Environment%3A%20MSYS2_ARCH%3Dx86_64,%20MSYS2_BITS%3D64,%20MSYSTEM%3DMINGW64,%20METHOD%3Dcross" -OutFile roswell.zip;
  - 7z x roswell.zip -oc:\bin\
  - C:\MinGW\msys\1.0\bin\bash -e -l -c "find /c/bin" # testing mingw
  - c:\bin\roswell\ros --version
  - c:\bin\roswell\ros install ccl

