platform: x64
 
cache:
  - c:\cache

environment:
  CACHE: 'c:\cache\'
  SBCL_HOME: 'C:\Program Files\Steel Bank Common Lisp\1.4.2\'

install:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) # for rdp in the vm
  - ps: If(!(test-path $ENV:CACHE )) { mkdir $ENV:CACHE; }
  # TODO If (Test-Path c:\cache\...)
  - ps: Invoke-WebRequest -UserAgent wget -Uri "https://beta.quicklisp.org/quicklisp.lisp" -OutFile $ENV:CACHE\quicklisp.lisp;
  - ps: Invoke-WebRequest -UserAgent wget -Uri "https://superb-sea2.dl.sourceforge.net/project/sbcl/sbcl/1.4.2/sbcl-1.4.2-x86-64-windows-binary.msi" -OutFile $ENV:CACHE\sbcl.msi
  - cmd: start /wait msiexec /i %CACHE%\sbcl.msi /quiet /qn /norestart /log sbcl-install.log # INSTALLDIR="c:\bin\sbcl"
  - cmd: '"C:\Program Files\Steel Bank Common Lisp\1.4.2\sbcl" --noinform --non-interactive --load %CACHE%\quicklisp.lisp --eval "(quicklisp-quickstart:install)"'
  - ps: copy-item ci/sbclrc -destination $HOME/.sbclrc
  - ps: add-content -path $HOME/.sbclrc -value '(push "c:/projects/redmoon/" asdf:*central-registry*)'
  - ps: cat $HOME/.sbclrc
  - cmd: '"C:\Program Files\Steel Bank Common Lisp\1.4.2\sbcl" --noinform --non-interactive --eval "(ql:quickload :redmoon.test)" --eval "(asdf:test-system :redmoon)"'

# TODO Load some dependencies first (for potential caching).
# TODO Tell asdf where to load redmoon from.
# TODO Run the tests 
# TODO sbcl --noinform --eval '(ql:quickload :redmoon)' --eval '(sb-ext:save-lisp-and-die "redmoon.exe" :executable t)'

build: off
test: off



